apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hoth
  name: hoth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoth
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hoth
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
