apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: httptest
  name: httptest
spec:
  containers:
  - image: kennethreitz/httpbin
    name: httptest
    resources: {}
    readinessProbe:
      httpGet:
        path: /status/200
        port: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
