apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mp-hello
  name: mp-hello
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep infinity
    image: alpine
    name: mp-hello
    resources: {}
  - image: nginx
    name: nginx
  - image: redis
    name: redis
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
