apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myenv
  name: myenv
spec:
  containers:
  - args:
    - sh
    - -c
    - printenv && sleep 1h
    image: alpine
    name: myenv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
