apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: myredis
  name: myredis
spec:
  containers:
  - image: redis
    name: myredis
    resources: {}
    livenessProbe:
      exec:
        command:
        - redis-cli
        - PING
    readinessProbe:
      exec:
        command:
        - redis-cli
        - PING
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
