## k run mypod --image=nginx --restart=Never --port=8080 --env=name=value --requests=cpu=50m,memory=50Mi --limits=cpu=100m,memory=100Mi  --labels=exam=ckad --dry-run=client -o yaml -- sh -c 'echo hello; sleep 3600'> single-run-command.yaml
## deprecate requests,limits
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    exam: ckad
  name: mypod
spec:
  containers:
  - args:
    - sh
    - -c
    - echo hello; sleep 3600
    env:
    - name: name
      value: value
    image: nginx
    name: mypod
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
