apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - sh 
    - -c 
    - "ls; sleep 3600;"
    image: busybox
    name: busybox
    resources: {}
  - args:
    - sh 
    - -c
    - "echo 'Hello World'; sleep 3600;"
    image: busybox
    name: busybox2
    resources: {}
  - args:
    - sh
    - -c
    - "echo 'this is the third container'; sleep 3600;"
    image: busybox
    name: busybox3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
