apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    db: redis
spec:
  selector:
    matchLabels:
      db: redis
  template:
    metadata:
      labels:
        db: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"